### ISSUE TITLE
Crash starting WarmRoast

### ISSUE THREAD

**Issue by Eufranio** [sk89q/WarmRoast#10]
```
java.lang.SecurityException: attempt to add a Permission to a readonly Permissions object
        at java.security.Permissions.add(Permissions.java:126)
        at java.security.Policy$UnsupportedEmptyCollection.add(Policy.java:827)
        at sun.rmi.server.LoaderHandler.getLoaderAccessControlContext(LoaderHandler.java:1005)
        at sun.rmi.server.LoaderHandler.lookupLoader(LoaderHandler.java:881)
        at sun.rmi.server.LoaderHandler.loadClass(LoaderHandler.java:404)
        at sun.rmi.server.LoaderHandler.loadClass(LoaderHandler.java:186)
        at java.rmi.server.RMIClassLoader$2.loadClass(RMIClassLoader.java:637)
        at java.rmi.server.RMIClassLoader.loadClass(RMIClassLoader.java:264)
        at sun.rmi.server.MarshalInputStream.resolveClass(MarshalInputStream.java:219)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
        at sun.rmi.server.UnicastRef.unmarshalValue(UnicastRef.java:326)
        at sun.rmi.server.UnicastServerRef.unmarshalParametersUnchecked(UnicastServerRef.java:592)
        at sun.rmi.server.UnicastServerRef.unmarshalParameters(UnicastServerRef.java:580)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:310)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
        at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
        at javax.management.remote.rmi.RMIConnectionImpl_Stub.queryNames(Unknown Source)
        at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.queryNames(RMIConnector.java:847)
        at com.sk89q.warmroast.WarmRoast.getThreadMXBean(WarmRoast.java:141)
        at com.sk89q.warmroast.WarmRoast.connect(WarmRoast.java:132)
        at com.sk89q.warmroast.WarmRoast.main(WarmRoast.java:327)
```

**Comment by sk89q** [comment]
No idea to be honest.

**Comment by Eufranio** [comment]
:/

**Comment by Eufranio** [comment]
I tried replacing WarmRoast, replacing the server, tested in another system, and i get always the same error.
Also, i downloaded Warmroast from WarmRoastSetup repo, from Robotia.

**Comment by sk89q** [comment]
OpenJDK or Oracle JDK? Version of Java? for the JDK & the JRE that you run the server under

**Comment by Eufranio** [comment]
Oracle JDK, version 1.8-u101, same for JRE.

**Comment by Eufranio** [comment]
Blaming xKit now, after removing it, WarmRoast worked: https://github.com/caoli5288/xKit/issues/5
