### ISSUE TITLE
ServiceConfigurationError: sun.tools.attach.WindowsAttachProvider not found using AdoptOpenJDK 16

### ISSUE THREAD

**Issue by Pieter12345** [sk89q/warmroast#20]
Using AdoptOpenJDK 16 on Windows 10, I'm getting the following error on startup:
```
java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.WindowsAttachProvider not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1383)
        at jdk.attach/com.sun.tools.attach.spi.AttachProvider.providers(AttachProvider.java:259)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.list(VirtualMachine.java:144)
        at com.sk89q.warmroast.WarmRoast.main(WarmRoast.java:246)
```
The application continues and I am able to select the Java process that I wish to monitor. When I do so, I get the following exception after which the application terminates:
```
Sampling set to stop in 5 seconds.
Starting a server on /0.0.0.0:23000...
Once the server starts (shortly), visit the URL in your browser.
Note: The longer you wait before using the output of that webpage, the more accurate the results will be.
com.sun.tools.attach.AgentLoadException: Agent JAR not found or no Agent-Class attribute
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:159)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:538)
        at com.sk89q.warmroast.WarmRoast.connect(WarmRoast.java:122)
        at com.sk89q.warmroast.WarmRoast.main(WarmRoast.java:327)
```

**Comment by ProsperCraft** [comment]
I think this may be the same, I am getting this with OpenJDK 64-Bit Server VM 21.9 (build 17+35, mixed mode, sharing)

`
Attaching to PID 3679...
[0.438s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[0.513s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
------------------------------------------------------------------------
Starting a server on /0.0.0.0:22000...
Once the server starts (shortly), visit the URL in your browser.
Note: The longer you wait before using the output of that webpage, the more accurate the results will be.
com.sun.tools.attach.AgentLoadException: Agent JAR not found or no Agent-Class attribute
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:160)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:538)
        at com.sk89q.warmroast.WarmRoast.connect(WarmRoast.java:122)
        at com.sk89q.warmroast.WarmRoast.main(WarmRoast.java:327)

`

**Comment by Pieter12345** [comment]
@ProsperCraft This indeed is caused by the same issue, being that a jar file that is being depended on is no longer available on JDK 16. Developers haven't responded for months now, so he only solution I see is to use another JVM profiler/sampler that is compatible with the more recent versions of Java. I do however like the simplicity of Warmroast, so I do plan on switching back if they do a compatibility update.

**Comment by ProsperCraft** [comment]
Did you find a working alternative for headless linux?

**Comment by Pieter12345** [comment]
Using Linux as a client, SSH'ing into your server with the `-X` option works to open the VisualVM GUI through SSH, but I haven't been able to get this working with a Windows machine as a client using WSL.
