### ISSUE TITLE
No class definition found

### ISSUE THREAD

**Issue by branchow** [sk89q/warmroast#7]
Trying to get WarmRoast to run in a CentOS VM and receiving the following:

```
# java -Djava.library.path=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.75.x86_64/jre/bin/java -cp PATH_TO_JDK/lib/tools.jar:warmroast-1.0.0-SNAPSHOT.jar com.sk89q.warmroast.WarmRoast --thread "Server thread"
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AttachNotSupportedException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getMethod0(Class.java:2856)
        at java.lang.Class.getMethod(Class.java:1668)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AttachNotSupportedException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 6 more
```

```
# java -Djava.library.path=/usr/bin/java -cp PATH_TO_JDK/lib/tools.jar:warmroast-1.0.0-SNAPSHOT.jar com.sk89q.warmroast.WarmRoast --thread "Server thread"
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AttachNotSupportedException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getMethod0(Class.java:2856)
        at java.lang.Class.getMethod(Class.java:1668)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AttachNotSupportedException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 6 more
```

Any ideas on what may need to change in the command?

**Comment by soulgriever** [comment]
"PATH_TO_JDK" not sure what it is for centOS but on ubuntu its usualy "/usr/lib/jvm/java-7-openjdk-amd64"

**Comment by sk89q** [comment]
AttachNotSupportedException is in tools.jar so you need to change "PATH_TO_JDK/lib/tools.jar" to actually point to tools.jar.

**Comment by APolarBaer** [comment]
no matter how i try pointing to tools.jar it gives me this

**Comment by naemr** [comment]
Although this ticket is old, figured I would give the solution.

Make sure openjdk-8-jdk-headless is installed note the -jdk- instead of -jre-  this comes with everything needed by this project. You will still want openjdk-8-jre-headless installed for things such as minecraft servers.

**Comment by rickdgray** [comment]
Thanks naemr, that helped me out.
